const test = require('node:test');
const assert = require('node:assert/strict');
const Database = require('better-sqlite3');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
const { safeName, tablesInDependencyOrder, postgresTableSql,
  normalizePgRow, columns, sourceRows, primaryKeyColumns } = require('../scripts/postgres-import-lib');

test('PostgreSQL staging schema translation and dependency order', () => {
  const sqlite = new Database(':memory:');
  try {
    sqlite.pragma('foreign_keys = ON');
    sqlite.exec(`CREATE TABLE parent (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT DEFAULT "",
      created_at TEXT DEFAULT (datetime('now'))
    );
    CREATE TABLE child (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      parent_id INTEGER NOT NULL REFERENCES parent(id),
      amount REAL NOT NULL,
      CHECK(amount != 0)
    );`);
    const ordered = tablesInDependencyOrder(sqlite);
    assert.deepEqual(ordered.map(table => table.name), ['parent', 'child']);
    const parent = postgresTableSql('parent', ordered[0].sql);
    const child = postgresTableSql('child', ordered[1].sql);
    assert.match(parent, /BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
    assert.match(parent, /DEFAULT ''/);
    assert.match(parent, /to_char\(timezone\('UTC', now\(\)\)/);
    assert.match(child, /DOUBLE PRECISION/);
    assert.match(child, /amount <> 0/);
    assert.throws(() => safeName('public; DROP TABLE users'), /Unsafe/);
    assert.deepEqual(normalizePgRow({ id: '1', parent_id: '2', amount: 2.5 },
      columns(sqlite, 'child')), { id: 1, parent_id: 2, amount: 2.5 });
  } finally {
    sqlite.close();
  }
});

test('full current schema and rows load into an in-memory PostgreSQL engine', async () => {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'payvexis-pg-test-'));
  process.env.DB_PATH = path.join(folder, 'source.db');
  process.env.JWT_SECRET = 'test-secret-only';
  process.env.DEMO_SEED = 'false';
  process.env.NODE_ENV = 'test';
  const { db, initDB } = require('../server/database');
  const { migrateLedger } = require('../server/migrations/001_ledger');
  const { migrateAdminControls } = require('../server/migrations/002_admin_controls');
  const { migrateIdentityOwnership } = require('../server/migrations/003_identity_ownership');
  const { migrateCustomerIdentity } = require('../server/migrations/004_customer_identity');
  const { migrateSharedAccounts } = require('../server/migrations/005_shared_accounts');
  const { migrateAdminWorkspace } = require('../server/migrations/006_admin_workspace');
  const pg = new PGlite();
  try {
    initDB();
    if (!db.prepare("SELECT 1 FROM users WHERE role = 'admin'").get()) {
      db.prepare(`INSERT INTO users (email, password_hash, first_name, last_name,
        account_number, role) VALUES ('admin@example.com', 'hash', 'Test', 'Admin',
        '0000000000', 'admin')`).run();
    }
    db.prepare(`INSERT INTO users (email, password_hash, first_name, last_name,
      account_number, role, balance) VALUES (?, 'hash', 'Test', 'Customer', '1234567890', 'user', 10.25)`)
      .run('customer@example.com');
    migrateLedger(db); migrateAdminControls(db); migrateIdentityOwnership(db);
    migrateCustomerIdentity(db); migrateSharedAccounts(db); migrateAdminWorkspace(db);
    const tables = tablesInDependencyOrder(db);
    await pg.query('CREATE SCHEMA stage');
    await pg.query('SET search_path TO stage, public');
    for (const table of tables) await pg.query(postgresTableSql(table.name, table.sql));
    let copied = 0;
    for (const table of tables) {
      const info = columns(db, table.name);
      const names = info.map(column => column.name);
      const rows = sourceRows(db, table.name);
      const insert = `INSERT INTO ${safeName(table.name)} (${names.map(safeName).join(', ')})
        VALUES (${names.map((_, index) => `$${index + 1}`).join(', ')})`;
      for (const row of rows) await pg.query(insert, names.map(name => row[name]));
      const result = await pg.query(`SELECT * FROM ${safeName(table.name)}
        ORDER BY ${primaryKeyColumns(db, table.name).map(safeName).join(', ')}`);
      assert.equal(result.rows.length, rows.length, table.name);
      result.rows.forEach((row, index) => {
        assert.deepEqual(normalizePgRow(row, info), rows[index], `${table.name} row ${index}`);
      });
      copied += rows.length;
    }
    const indexes = db.prepare(`SELECT name, sql FROM sqlite_master
      WHERE type = 'index' AND sql IS NOT NULL ORDER BY name`).all();
    for (const index of indexes) {
      safeName(index.name);
      await pg.query(index.sql);
    }
    assert.equal(tables.length, 31);
    assert.ok(indexes.length > 0);
    assert.ok(copied > 0);
    const ledger = await pg.query(`SELECT COUNT(*)::int AS n FROM ledger_accounts a
      WHERE a.balance_minor <> COALESCE((SELECT SUM(p.amount_minor)
        FROM ledger_postings p WHERE p.account_id = a.id), 0)`);
    assert.equal(ledger.rows[0].n, 0);
  } finally {
    await pg.close();
    db.close();
    fs.rmSync(folder, { recursive: true, force: true });
  }
});
